apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-pg
  namespace: nextcloud
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  env:
  - name: TZ
    value: Europe/Stockholm

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-postgres
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  storage:
    storageClass: longhorn
    resizeInUseVolumes: true
    size: 10Gi
  walStorage:
    storageClass: longhorn
    resizeInUseVolumes: true
    size: 5Gi
