apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-pg
  namespace: nextcloud
spec:
  instances: 1

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-postgres

  storage:
    size: 1Gi
