---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-admin-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAvFtf+UIAObRFPjjma66YoffZHdt7plzdML8zDIOjohMDqZuiLzQRWWJ2sIPACggjeXZAVse5WpP0x+zuyPQIMLJiYpiRoGPMVU+rr2tw3jqhOYOOpeeGlIyYrNSM+a3a0ivPas7RxQjoLa3x2kJmDW28saCiX7b8oh5jAwjZgNOzerESvXW9OnoPm/HpdreUXZFb9P+OS48BfRCBJl/5bFmQwSbUT2nKPze6zzXULlhlbPo+prBnak38IFqW9DrbBqm3h9nh6f6WlptRjeOn27Mkgn0HOXhj6nWEM2/HoZg6BH8Vo1+u6NrWwictWY7OLpr3lJ2yBQB2eUABREtN16p2U0uoojCxHeVZidd680h4c5tQjhT2IdG5BP0kaFwz3TzjPSg1oM+ANsZ6cl0V5Xd0OGm3V4KJbR4YHV3v2IM3A6SqSvhtDTzBHaIh0DyiB00sxWymf1MZEnI/KgMCgAZBv3snGEj1bB56UXFhRao4svg5KpD1CsSY3qbK9LOAYy+0C9aB/wP048GIkAoG5/X7C3HxReoAjTafR2NjkGIbeJWx9gIH4jJ7Z04sSeLNFEG7kba69MCukDBXF9aCHIBdCoP6QF9Pqs8jVUN67vmVeyQ484JPFE0+/6v2h8kbcya9mtKPkJ75btxqLZvM1gJddJr0QxCVXZ8gv2Si9bWD8U7C/RyUCtaJpq2lC5OVkQGTtOCTW2N9x+jBVdPp6nZKTT6NMvWQ/xFNu5/WN5mo++lCYUqZo
    nextcloud-username: AgAE40Qq9n1pydJHIzn579lPyifRdZAVAPB8iObzs21WxZgTtz8wk3SJ6viSrZv9QSen7F3SEhItdbo+E8u3BUTlHTlXUU2wTc+cZQPXm5LyY5MtOkwu/uHGNDQxPdoVX17dPbEQh7lGRq4rgIpjy4DhIXjg52Rp+VIbQrOPrfyiFgjHSCh3P1tTuz0gnAbz1Hzp3wjNZpwk7zuvkLkjzWwnHpEhXFAQm+s8a9F+oXUUEmHTko8xi3gO8c41sjcDTZ70puaFgPUdrV/6i7VmVmyojt4aw/9kekLCstE1IRn3zR4Z7tQPCtyWB24D2iPWTzqCJJxu0Jy95HBpKt5n3qzsXvm/fVSKXgmlXRNBZzXxndT2O5ucYv4gw/cmyVIdxHo9LzT49eXYQvNIPR6ARPh1gWL7/QSWIAE+C0svdMxn/UPGPqdpQqEVYDl4+z68jcCPFftjUFRIshrhZzCQO1t6thUVPLFk6uVbqQCA9xWHAdo8z5e90G0b2KGT0CId0qe4Dlpz3W04okz+q3ZDIgIEwooxLETRAgEajuPQXE63xlFqJD8h5ZmZxSXCj8508EvRhLqH89kdIQNw5/yryVUiZEzsmZrtXx+TqNLPj8yv2HxfXO67BC3vQjjGLfgJFZZysSHwbZ5ak94TbOUJaovMgKKq8vJfUbh/rcabeyAKuPhvlx85ujhlajr7Tl4FXiIJyop1kA==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-admin-secret
      namespace: nextcloud
