ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  className: nginx
  enabled: true
  tls:
  - hosts:
    - nextcloud.rre.nu
    secretName: nextcloud-tls

nextcloud:
  host: nextcloud.rre.nu
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usenameKey: nextcloud-username
    passwordKey: nextcloud-password

cronjob:
  enabled: true

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-postgres
    usernameKey: username
    passwordKey: password
    hostKey: hostname
    databaseKey: db-name

persistence:
  enabled: true
  size: 40Gi
  storageClass: longhorn
rbac:
  enabled: true
redis:
  enabled: true
  auth:
    enabled: true
    password: ""
    existingSecret: nextcloud-redis-secret
    existingSecretPasswordKey: redis-password
  global:
    storageClass: longhorn
