apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-cumin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  generators:
  - git:
      repoURL: https://github.com/SweBarre/home-k8s
      revision: main
      directories:
      - path: cumin/infrastructure/*
  template:
    metadata:
      name: 'cumin-{{path.basename}}'
      finalizers: []
      labels:
        rre.nu/type: infrastructure-core
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/SweBarre/home-k8s
        targetRevision: main
        path: '{{path}}'
        kustomize: {}
      destination:
        server: https://10.2.0.22:6443
        namespace: argocd
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - Replace=false
        - IgnoreMissingTemplate=true
