apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: nginx
    version: 21.1.23
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: my-nginx
    namespace: test-nginx
