apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - cloudflare-api-token.yaml
  - cluster-issuer-prod.yaml
  - cluster-issuer-staging.yaml

helmCharts:
  - name: cert-manager
    version: v1.19.0
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
