apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup-job
  namespace: mariadb
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: mariadb-backup
        spec:
          containers:
          - name: mariadb-backup
            env:
            - name: ROOT_PASS
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-root-password
            image: docker.io/bitnami/mariadb:12.0.2-debian-12-r0
            command:
              - /bin/bash
              - /backup-scripts/mariadb-dump-script
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
            - name: backup-scripts
              mountPath: /backup-scripts
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mariadb-backup
          - name: backup-scripts
            configMap:
              name: mariadb-backup-scripts
              items:
                - key: mariadb-dump-script
                  path: mariadb-dump-script
