apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - mariadb-secret.yaml
  - mariadb-lb-svc.yaml
  - mariadb-backup-script.yaml
  - database-backup-job.yaml

helmCharts:
  - name: mariadb
    version: 22.0.0
    repo: https://charts.bitnami.com/bitnami
    releaseName: mariadb
    namespace: mariadb
    valuesFile: values.yaml
