apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-0
  name: mariadb-lb
  namespace: mariadb
spec:
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.100.100.21
  ports:
  - port: 3306
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-0
  type: LoadBalancer
