apiVersion: v1
data:
  mariadb-dump-script: |
    #!/bin/bash
    umask 0077
    databases=$(mariadb -B \
        -u root \
        --host=mariadb \
        -p${ROOT_PASS} \
        -e "SHOW DATABASES;" | tr -d "| " | grep -v Database)
    for db in ${databases[@]}; do
        if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] && [[ "$db" != "sys" ]]; then
            echo "Dumping database: $db"
             mariadb-dump -u root \
                 -p${ROOT_PASS} \
                 --host=mariadb \
                 --databases $db | gzip > /backups/$(date +"%Y-%m-%d_%H-%M-%S")_$db-sql.gz
        fi
    done
    # Delete the files older than 3 days
    echo "removing old mysql dumps"
    find /backups/* -type f -name *-sql.gz -mtime +3 -exec rm {} \;
    umask 0022
kind: ConfigMap
metadata:
  name: mariadb-backup-scripts
  namespace: mariadb
