---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb
  namespace: mariadb
spec:
  encryptedData:
    mariadb-root-password: AgBBCPmyXr6y0WzKB52yxYYbnYKf9ld4SlFE+Xna57F/sd6t0yZb7tB54GI2WFqHqaHwCd5+WlXKKhKM8BOsAdO5YBvRYnGo6Ycrhc40JAJ70VNcATkueJBE8ovLf59v66Xq4CqKRoHJM19h36grSEyuGAilEtwLtp/4vnqY2rKJPDZ2SQ/rgb2kVWOYJCY9eziVCgrmh+yXr9VWjynCGREMiYl69ZeLVsnONfRYybEKNxQUOdr9zmvtHk5zMbtUFWZdC6lnhGqQ9xxW1UmiGFMX7Ikw7UVLbpfjxjrShtA5kteoum5yEJO9Im1R2wfBTKpgO9N28rpF4WUIFctiLfQ3OQVHpvUyYPz9+apbMJ3GXfVdv0h9/MQJUVKuGAqP9Tf78gqieZbSNkPUIYta/WtqeYyHMf7LndLGIbzWLYNg2qfN8D+qZCwWq9g8ktd8FoCvjfMArUiL2w1vqoonxmDH+nRDQWSuYJfnqAl5A1o8WvuLwg+gY5fjkCTYaw3jo/mPfZtp2ki5Dc2gw91yqfRFSzyg8o1IRYttBNk8oJNUo0+SZEa1ySXSIDZiIxsS9yYPLowGCih/KhWoRI985tg9K2AHgUMhKFQQpHl8dVcnwm2cSKxh7Sdt6h38jY83dGOtE/MjjMLDwvwSL0ckvWdDwu4uER3tAP0TceLkqNq9mV/X1c4KIjjrd+kwDWT2cdpMuc9NKSGp6+vbYmsbPV0I9GtYDmRV9SoHDpt+X6rfSA/+AFiUEgk=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb
      namespace: mariadb
    type: Opaque
