global:
  domain: argocd.app.rre.nu
config:
  params:
    server.insecure: "true"
  cm:
    kustomize.buildOptions: "--enable-helm"

#  oicd.config:
#    name: RRE
#    issuer: https://auth.rre.nu/application/o/argo-cd/
#    clientID: CLIENT_ID
#    clientSecret: $oidc.azuread.clientSecret
#    requestedScopes:
#      - openid
#      - profile
#      - email

server:
  ingress:
    enabled: false
    tls: true
    hostname: "argocd.app.rre.nu"
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/service-upstream: "true"
