apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - pihole-admin-secret.yaml

namespace: pihole

helmCharts:
  - name: pihole
    version: 2.34.0
    repo: https://mojo2600.github.io/pihole-kubernetes/
    releaseName: pihole
    namespace: pihole
    valuesFile: values.yaml
