apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: unifi
spec:
  clusterIP: 10.43.172.50
  clusterIPs:
  - 10.43.172.50
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mongodb
    port: 27017
  selector:
    name: mongo-db
