apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unifi-ctrl
  namespace: unifi
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: unifi-ctrl
  serviceName: unifi
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: unifi-ctrl
      name: unifi-ctrl
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Stockholm
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: unifi-settings
              key: MONGO_USER
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: unifi-settings
              key: MONGO_PASS
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              name: unifi-settings
              key: MONGO_DBNAME
        image: docker.io/linuxserver/unifi-network-application@sha256:78abb3540cba315c9fcb0f91370f5eb3070a61349df63b20a9ea42c4a95af4bf
        imagePullPolicy: IfNotPresent
        name: unifi-ctrl
        ports:
        - containerPort: 3478
          protocol: UDP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8843
          protocol: TCP
        - containerPort: 8880
          protocol: TCP
        - containerPort: 6789
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: unifi-ctrl
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: unifi-ctrl
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: longhorn
      volumeMode: Filesystem
