---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    password: AgBXTpsLBBpggZHyc4FVpaf5V9ewDQjwnmTjcWtOi9IVIMOKtZFyNxA6z6bs60X10ZBTgMcyDQc9XACcAxqMbtWGUsZz4wk3sOclojQXWmegL4NNTNW0SSGviA9DC+4+f0/0t74KDLLjd8oVFnPP2GM1tDXpP30U+l0LZhtZ3AXg4EDkJrMMHnyTlolLwNFLKJWJ0SXV9FAHAvmV/8wRnP6rysM19p/8uP6mCc04UqmAsXNckB/+dcAwmM9Ol8r2sOJAfMz9UQpppR3bSj7rvpjx+w6+309hto8Md2Snjh2SYHqEvf/GxhKIeLtrcIYAu0kRh03RNkpPbYAhljbElFpGAdhUCPyf0G7g8MJV9UYPt+hNEQ0+tMuZTxwGhrVeTG+jY/TpmUzT+AE3H6VJgPikIs3gU8qfyoD2xTjTxUTwyklns29xJPYAuya9lsagENDCjCecSRagdhUTL2ccFzgkbqRrLeQg03o6FNAxdQfIZXYMRlyHWC9MWYrxzbj2JAjxK+IyNMlGR7mfMX5HaAKYWvarDiilLuuBMTIrOXm4yJuy6JzeTBW0sr0VIxOPizNlDHookxgGRd0iSsOP/dpqcpd+QutlyAe+O+MCsr2GxbSfxmUKiV1kSAAc3ayTLhOR8sSiwYYylXQKVtQ0DW6bTI+gsN9zAtOsfHDTWB3gY8MeIRJiHu7L80dUG16LYReVS4jN75L3j90zxpzLxgP7N4TnVse4QEWopUtyN0Zd/AAxs3JyxcZ9
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor
