global:
  domain: argocd.app.rre.nu
config:
  params:
    server.insecure: "true"
  cm:
    kustomize.buildOptions: "--enable-helm"

crds:
  install: true

#  oicd.config:
#    name: RRE
#    issuer: https://auth.rre.nu/application/o/argo-cd/
#    clientID: CLIENT_ID
#    clientSecret: $oidc.azuread.clientSecret
#    requestedScopes:
#      - openid
#      - profile
#      - email

repoServer:
  containerSecurityContext:
    readOnlyRootFilesystem: true
  volumes:
    - name: cmp-kustomize-build-with-helm
      configMap:
        name: argocd-cmd-params-cm
    - name: cmp-tmp
      emptyDir: {}
  extraContainers:
    - name: kustomize-helm
      image: alpine:3.19
      command: ["/bin/sh", "-c"]
      args:
        - |
          apk add --no-cache curl bash git helm kustomize &&
          sleep infinity
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools

  extraVolumeMounts:
    - name: custom-tools
      mountPath: /custom-tools

  volumes:
    - name: custom-tools
      emptyDir: {}

server:
  ingress:
    enabled: false
    tls: true
    hostname: "argocd.app.rre.nu"
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/service-upstream: "true"
