controller:
  allowSnippetAnnotations: true
  config:
    annotations-risk-level: Critical
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "requestID": "$req_id", "proxyUpstreamName":
      "$proxy_upstream_name", "proxyAlternativeUpstreamName": "$proxy_alternative_upstream_name","upstreamStatus":
      "$upstream_status", "upstreamAddr": "$upstream_addr","httpRequest":{"requestMethod":
      "$request_method", "requestHost": "$server_name", "requestUri": "$request_uri",
      "status": $status,"requestSize": "$request_length", "responseSize": "$upstream_response_length",
      "userAgent": "$http_user_agent", "remoteIp": "$remote_addr", "referer": "$http_referer",
      "latency": "$upstream_response_time s", "protocol":"$server_protocol"}}'
  defaultBackend:
    enabled: true
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: mon
      enabled: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.2.0.40
    externalTrafficPolicy: Local
    type: LoadBalancer
fullnameOverride: ingress-nginx
