apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeseal
resources:
  - ns.yaml
helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: "2.17.4" # It's good practice to pin the chart version
    releaseName: sealed-secrets
    namespace: kubeseal
