---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    api-token: AgBDSoCQL36s4BhujMPhtedEVrLWtoWy7zD23psjXasoWIMH+Qo1OjR2I9rgLQz9VXqidap3Uu1SG7feR95oadVPUzGJ7B2YrkRwpGXG4TUEiZW/VzsQVrN8weOTCG0LUFjxSEql4EaHR8Dh686z/icYGWv8MXFqCZ25847ycM4daZOawEy/gzKIiZ7LmOqZrcCB2Xv2tjwrvSsXR2VLJsOTq5ukTHuSRf7lx62IS/mnhJNNO8xUJc2/b5JX/LdrziSnB3I6YOpIKaOPl/PWEmQtwaz0Wdv6D7u62n7l5ihz0H5MmOg89s8+4/ZURJLIbASBD7cA/01+2baEe3hjkG1D7VYGEbT3QXa2nSVeJmqFBucKxhN6UItiwRu1DF0MYBsDf+fStR7Y3TxP7vFoF77DqBDHehuOkhR5auVG8S7CZLG+Rqtbs/g43Jl/WuH9yHtmpqMybB9vGOqND5okgkRKxbtnAM8TfXIDmTLswejUjh+4CsnJWz8u3PdVQCze6DR6l8Q4zAX0hfkvFO4Q6qUyVB36UKvo0yX5kaU0+mrOh0UJFsFRQEk+kbZ6yJCxOcCnwJ2/xHck8sURESOJmu/HmMkAbLkdQWee0oWGSW6mHktp1OHQ/ZBWjcigx8DrnT5OsqynCC75+48mOGGQ8b1FA06XN4Lwmj9Wg+sQtj2yD/MasukgGwZbAQPBBD5g9uxOszH4kJGZ6GyA7gjxp2OLEGOv0kDM+cEJwhiFfA2q4Esp1DvNMimz
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
