---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-pg-user
  namespace: immich
spec:
  encryptedData:
    password: AgBOHWv+JU4YApRX3ETd6khRrE9BwTp6T6WvXVMqxzEyRxA4+5LAb9YzFddxTGg6xqRtYeYx1rReqcE9VYm2ZjqG2+zHFHQQFNGCFuD0uwpL7ll9CRW2jIxZ3zHsHx+f13k6k9T8REubFnTMlNAI5N01eq5JnUwlqf7moDBDbDkDJ638mJ7qrWvYE1YUlssWwnCH72jD9445HbIECoFIbODh+Yl8UpgBw4SOuL25zUXE1uNfdnjwzYAiq/iedD+NggqS8zRi6rrBdLlQXwQyWaAA9ddi43o7PU/44qbzZHnqEHmrbsUplpzt/ND+peNwcPaeluXzm99ZJh1zKxkIYvaudMlm5AmfLoRowfTlIuF3uhW1A9eDbAwpUV296i4CpHcFQ9W9NcLwGIkiOrVa9OFTpJetFzTW0zDypOPU5uTO/JpliKwGapFN/y1LOWUjftwkevvQkNXfOQR1THFmT+DkeKo4RRUZuCNzBrL9OLh+vUJRJo2quTIgBZ96MDeXPpW88ItywUz3A4imUfZptwca8y4SS109pZz1/cDy2XOdSulVUbE0D+4X3u6xeRjpyC5+sHHmQIOIWFAc3O/M2xVDeO4CPHG8u0Gckak93xiatdQpD2A1idib2Bk2VFbRkTzSOQHkTNHZzVLnMvSwXJJnMynieo9FazSlM3wZOvsrrIhZ7RQxiRmiDpYqQzfIMw2LGrQ//oOiFMpWDLtjHYGSduWWJwItWTsBBNFVvddyBq+SF6N9DTlOdHZT4Y1/HpX2GpK/sggzb9JqqDg5yYXf
    username: AgAvZJfimXDLd8Jyxvk/o6lKHIgKH4j69Zqq9p734uE1eKPTGN/7rXTWLE+S6jAUYpm8TIMqRMFPLBx4kUncy3FBCi+WwoRWoPXlWE97gKqNSBY092KRF8n5F9FrpmyZlSxF23Kuy9u8XEPspwBd5x4XYO+bOSWylzbPvUxq8chKnxOmYonbWvF7Tq16VFGR+ZIZDzMN/gkgOUQYUwcUTHvZyFhCkMso6IhCqrdBcq2DQmlaVQ+sSRhcbhbOfHFAiwyCWm7NjzSMhi0eWafCPVe+OhlFFFm1SMMDb/jeV2Mz3yYAFVo9/QeSzRQN98/6M8wHkRX4iPj/dezg6e7rpOLVUo1qs5Eyou0YU5VtJlHvtnPTRZaXiN1NrhULC8vdNa0SxLQgXWgFdlfr/X1gxzkQWt5ZM69w9NqaD5m1ns6qHMMQ7Gd9wjrh91rBC+BFrX2BOIXrnGupfecnSXEb/Kv3mgvNGJE85kiQfhYtVPA/FTjKqWtGw3/3gbpTLx0kZXdr10SalHzxNb11P+jghxk89yxuvu1yXnpnLTF2SR5zyFUIo2fug5oi/HqLfiOBIEYax9cjoFL4gsoQSHCZ90A0Z/9yCUuouTmH/kIS+CA2S7uvOLasvFokZZinPBEbDUI7YXZhQiF5z+0x2Ik4JQ/xeSGv0gJP0155+SRl+icbRAels2LYWTE0ZYifBw0JVj1alE8mZzQ=
  template:
    metadata:
      name: immich-pg-user
      namespace: immich
    type: kubernetes.io/basic-auth
