---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-pg-superuser
  namespace: immich
spec:
  encryptedData:
    password: AgC4pXYKsWN2DYFhw5b628tUUTVtXwlTCsfRVBGTwToZDX5Dnd7W9Mhan1VXtf9QF74cNBTbtBggYTONsANZLKMHMHy7P2QIKafMAlfqPQ6t9O1cRMNlsDuTTR73RFkxX7ZJPMCXqjiuJhs/xouHRDAYcaDYzsa1kL2KRlRPIAa8h4NfoI5IqnhwR43gQZqizp4RgcAsbngDDlHligBJ+G8yeqEitqN1mAGn8omulhaH76jXLBsQAx+7N+U9TvNTjd6/Z6+aUUovkx4IQmbjcLYz0AT0SZBNgQGgbJYPlgb3GR40DZnZpInvCTfVrgEKBI0RXwjcEEqZDLx/er3ZmvUX9M84skl5dzniqBWilZ+/exUvJKqxB2tD68ZbloDaz8q3X0G8gWOIXH7qjPHMq4TUzT2iL09uwwk4o+BWbDMbNG5/+VwEUit4veqzFp06g9hYCWDjH4IrLnCKOCtnR17CofAVmbj0UvKytylBSPxdv45Z6YSHHrCY12eUisneM7I/6o7zUpZy+CNxjlcn3a+XJyO2kblZGeUcZ5z089BQq66O0IpluBKsD8BHo00UFlugxqiz9FTA31TzqAyH/PXDIFYNxVsRsDGKRahNt4Hit9l3mA9mhzlDWdKVQ2T26Cmoaf9x+Q8od2JFDws30Ecau0W4xf7HWJMrnKAOAr1+ASt+tiTO8VxfJNbWJEKqcRwQY/TtKi4u3Syk4Ugpk4ta2a4BxmB2HGK4Yj7I9Cbf/e5d60C2SneX
    username: AgC1ygpfNj2TYfbAflYvPiWCG/HycZNYPhIOoSGnICpmv2tRe/09fFLcKWts4H2GPVmcDRb9Yxk+sW3EG5iChKPakC0ETqgwZiKIYl8sWHcXY+Ey51bPtJzL1O5S4aNHaZH42TyIzbaoyAwLflp1/scYZA7zdYXJy9Nh6CfIYFJDx+EfIZGhQ9kR3/DfqNUmU3GU6O4wqnEvU4oZi7TdmE1EktvkQu85GhL+c+GHgb6h2u6S0Iyq+xPSgtC7H9+hgblbrh1I9n9qc4bjLFCFbhGz9beppuFtr4auuf2A0rJAh2m/BpBWVyKGQPRIUwtRTfJiRLAkKK+M03KoRKwRyoyyCYYzxJMjfyxsM298/sojm37AAIufcRvOOR8H0nD9Palr1rmCRO2XZZScV+erxMRzThPhU+buOBuL4pyKSfxg3L1z3DZfwS4f2TpNkHn+GLcmBVeUkNU3bTBpMh+AgszrtMmx3pEt3bTCFOOet7KoPiDSewUyJQRoWgKKsI2zteASuZtNdSXSIA7I6pEdS8RQ+qzNTOMPAk575cupO+YxAzTf7GQovuToEI8ADQEqVCnffztBK7KfZtwoywjFBM2LyraT4LziTjsG/yUtGNlnX330b9djYxxKT7FnM75mUqSHq3D+TP9CDu2exJxxSELS+lWAFDh0UVcXAgwOboFGlEib6FJNCcZhpXfP10Mfb5AyeaaEEsGBbQ==
  template:
    metadata:
      name: immich-pg-superuser
      namespace: immich
    type: kubernetes.io/basic-auth
