apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  namespace: immich
  name: immich-daily-db-backup
spec:
  schedule: "0 0 6 * * *"
  backupOwnerReference: self
  cluster:
    name: immich-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
