worker:
  config:
    sources:
      usb:
        deviceClassWhitelist:
          - "0e"
          - "ef"
          - "fe"
          - "ff"
          - "0451"
        deviceLabelFields:
          - "class"
          - "vendor"
          - "device"
