---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCkrwOLJlPzcbB3yGyKYJedzjrw5Zi5Hf/j677TuQpSNy3EFZK40yavkROsunohpX4CXFR1pxYPqXJIIrMsOeULypH0hf0qYvyKKlc33gTjUqqzV6zA2tbkhzkss7ggsMK1Gc66N7k5Xzk24Q3BIMJAdRbd7qblA+QBRYkXzVnO0MKHH49dEVRYSE5QNRwcl/Tb3cs8q1QAXyF5jPsdDTQDtB3rjerSddGTSYh+XCGtVrSZFK2fCApCmCC13w1xFBo4bhqRFVuZM2GUzk5YbetRn1si7BPOgVct9IS4miRa3aLqzdsJtXjkqDzXOJJqDjVvma9k9uqEX+jjGsWWCAjUjTk4oej/svJKaSazsNjXBNldO0c391K3Tx/Oz4AWVuNUSYgvfvkbwjuw13/jdT9y/D+RknCEG/IPuMLq5YCas+LVbIzDWmn7kvak7N1n4Z+PzBD5HT94jm91WdRGUw3Q5iy4xF/qUwLkC3OF2+IfDxgAEts8TTkQ6xG5kMan6ckRPC4uhB6ZoAu/Eu+OFYH15gS1mHo7JNlYxT+whTOx8IFVDiPbjAfszzsgY6u9UObCNe+wS6mDvLmLy7lH3YaQouRwIwM2SOMV3YHg9qUKqOZyNJqnseWUYT5ratbT416AIJybXAGaDQ0JAP7f1O4GDZoX/fVGpWFm/4krTDO+BIHm96NQuSSi16E3JYA7F5r/Z74B24aGYFBRQywhi05MypxtSF/fVcHDFYesU91LNO1VoIvnOONT
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
