---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBAyg+Ft8Htdqu7q/jXWaoYgwFG3/5vXn37+x7HLtdDvhekuI951W3rXANpxOn4bFmNuJ0I8Ox2zQUZ/ExxYVbNrFXMj0WAKxXPF47/0AX5zugrNmzA3aE1d6C/xGYHG+bbbyoaJ7sTHugcHggyLf8/MYzIN8RE7T/8mRwf3vXTQDTxnGqXXqA/G55rDLo8pm//yA9aoDo01HmokUllN1FCOVA+P7h449FxRLr3XClB8owRBMFtlv16lUTpq0iIqC14DAdJMDH7OvKpI8h6nmCXY1EtsqLvYnnVUz9HPf7mdOEXN/BVDOZgrNZlau71MzDozeqbg7Vz7gDL5FwsMCQOO1iUrle9ESqJKSSGZhRv6+zaCZX6FWs5MGjBGOTblBseV6N+U6GO5/QpSJnoVQGu02Z31whFuI9ps9Oi4xAs1p+dKNd7wBN/SI1kaMcYUoiTQWia1QUW4atZpuZfxGnqn6W2fZVPj1oDwopqrxdpR9DUx2Hl4WeH4MjdbLC8p6Y8NJhrBa3l5kyp2f3CKK8xoyv8SN+jUEnZ8NwMYomLZmnVCW9FEuIS1AWC1kmbrX9klIUpwy49fK+edFdlmpJy9yanBbGN3WhDGxT0XC9I54FGSqce9vSKhD6lUQP/9yvqGBajYojulukd3T/ClAF976XJD+pvtba2TFKShQmiOKYiy0ZN5Vh+KwuFSh4e2cIYzksiic2SjbfsnnqqF2EWwH7ax2GxvyDjIHThsJ8I0meUU+zZBArA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
