---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBzUNX2WCLgQide3II7H2LFgW52E8tMSjc7s7w/Cz+rfe6OjtsKSV64b3N6lJIAW+agYmljJlOcOLZDAv73q1pvu6JhWbXmbGp8Drt7yHrhoPe+nSUGbrce9to4Na9GVMvVSeT3LJ+T/WbtBVhJvldSYEgj/P28dn0FmRHTuLOcNEA1c1FCZls/ZmU/cVr3Wo3HMfLcHEb+wwK9vJ8JtTjoG8dM+EzIekFUimWg1SDLgAWIrpdnwdRKYMu45S4UuGjrOTF9VDlDqybldgg+4irRmnV9VU0g0fbFNsXxtwTW1bXzQEWnxyjkYC3m7f+cUyVwDKI22IF+z+PEbEHsP4OAFj26ysoMsdAzUZR2hYdNaKDFYmqQjLz9ExSPsimf4fUYbauFW1XhQhpv4vMdhGI/N8PMp12//FI4C7SlgOWMosUkKN/K/e4noZcJyNeQapzTEN0DYMN6CXANrZCUC9pf+yFpsLx7dYv320ALW8vKaK3fLjrhO9vAUMdW2AqJ18nd/U5Cv3u1I9zfJPEBr5XdpA0hDPFlwmM5kcKOdetrAR2eaphwou5bWnpjEXHGW8n1wawzNmvRknTkfPDOt4esrKz/O8xnggZ4YFxtYg1QtHimgueAjATx9hJEJnteSpn43ZlB/f02eMEEzVtqx7pt4X7ngnFjq+x41MqMOWYRGQE71DhSnXeLWmxqYAjfY01wDLbLg4hu1a+c0xGA9B9BNAgTE1FUX/fYC+kZ9C8G9Hkpj0haKutE
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
