apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-branding-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
