apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Core infrastructure components
  sourceRepos:
    - https://github.com/SweBarre/home-k8s.git
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: admin
      description: Admin role for infrastructure project
      policies:
        - p, proj:infrastructure:admin, applications, *, infrastructure/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Shared workload and components
  sourceRepos:
    - https://github.com/SweBarre/home-k8s.git
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: admin
      description: Admin role for platform project
      policies:
        - p, proj:platform:admin, applications, *, platform/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: User workloads
  sourceRepos:
    - https://github.com/SweBarre/home-k8s.git
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: admin
      description: Admin role for workloads project
      policies:
        - p, proj:workloads:admin, applications, *, workloads/*, allow
