extraArgs:
  - --enable-certificate-owner-ref=true
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
installCRDs: true
prometheus:
  enabled: false
  servicemonitor:
    enabled: false
    labels:
      release: mon
